# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rimi Biswas's Page
email: rb@domain.edu
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my site. It's just a plaything right now 
  so I don't have anything at the moment but may update it as I go on.
  Thanks for visiting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
